title: Page

columns:
  - width: 2/3
    fields:
      object01:
        type: object
        label: Object Field
        fields:
          text:
            type: textarea
          structure02:
            type: structure
            label: Structure Field
            fields:
              text:
                type: textarea
      blocks01:
        label: Blocks Field
        type: blocks
        fieldsets:
          - heading
          - text
          - quote
          - structure
  - width: 1/3
    sections:
      contentTranslator:
        type: content-translator
        label: Content Translator
        title: true
        # slug: true
